package hu.jinfeng.mybatis.provider;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;

/**
 * 注解字段
 *
 * @Author hujinfeng  @Date 2020/11/27
 */

@Target({METHOD, FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Column {
    /**
     * 表字段名 - 默认等于注解的属性名
     */
    String name() default "";

    /**
     * 忽略的字段
     */
    boolean ignore() default false;

    /**
     * 当没有设置表字段名时，默认驼峰对应关系。属性名 userName <-映射-> 表字段名user_name
     */
    boolean camelCase() default true;

    /**
     * (Optional) Whether the column is a unique key.
     * This is a shortcut for the UniqueConstraint annotation at the table level and is useful for when the unique key constraint corresponds to only a single column. This constraint applies in addition to any constraint entailed by primary key mapping and to constraints specified at the table level.
     */
    boolean unique() default false;

    /**
     * (Optional) Whether the database column is nullable.
     */
    boolean nullable() default true;

    /**
     * (Optional) Whether the column is included in SQL INSERT
     * statements generated by the persistence provider.
     */
    boolean insertable() default true;

    /**
     * (Optional) Whether the column is included in SQL UPDATE
     * statements generated by the persistence provider.
     */
    boolean updatable() default true;
}
